=== Unarmed1000/gtec-demo-framework/.Config/FslBuildGenConfig.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:annotation>
    <xs:documentation>
      Describes the FslBuildGen.xml configuration file format
    </xs:documentation>
  </xs:annotation>


  <xs:complexType name="_T_GenFile">
    <xs:annotation>
      <xs:documentation>Specifies the name of the gen file used by the tool</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Name" type="xs:string" use="required"/>
  </xs:complexType>


  <xs:complexType name="_T_TemplateFolder">
    <xs:annotation>
      <xs:documentation>Specifies the directory that contains the template files used by the build generators</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Name" type="xs:string" use="required"/>
  </xs:complexType>


  <xs:complexType name="_T_AddTemplateImportDirectory">
    <xs:annotation>
      <xs:documentation>Add a root directory</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Name" type="xs:string" use="required"/>
  </xs:complexType>


  <xs:complexType name="_T_AddNewProjectTemplatesRootDirectory">
    <xs:annotation>
      <xs:documentation>Add a directory that contains the templates FslBuildNew creates new projects from</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Name" type="xs:string" use="required"/>
  </xs:complexType>


  <xs:complexType name="_T_ContentBuilder_AddExtension">
    <xs:annotation>
      <xs:documentation>Define a input file extensions used by the builder</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Name" type="xs:string" use="required"/>
    <xs:attribute name="Description" type="xs:string" use="required"/>
    <xs:attribute name="PostfixedOutputExtension" type="xs:string" use="optional"/>
  </xs:complexType>


  <xs:complexType name="_T_ContentBuilder">
    <xs:annotation>
      <xs:documentation>Add a content builder</xs:documentation>
    </xs:annotation>
    <xs:group ref="_G_ContentBuilderCommandList"/>
    <xs:attribute name="Name" type="xs:string" use="required"/>
    <xs:attribute name="Executable" type="xs:string" use="required"/>
    <xs:attribute name="Parameters" type="xs:string" use="required"/>
    <xs:attribute name="FeatureRequirements" type="xs:string" use="optional"/>
    <xs:attribute name="Platforms" type="xs:string" use="optional"/>
    <xs:attribute name="DependencyFileOption" type="xs:string" use="optional"/>
    <xs:attribute name="Description" type="xs:string" use="required"/>
  </xs:complexType>


  <xs:complexType name="_T_ContentBuilderConfiguration">
    <xs:annotation>
      <xs:documentation>The content of the packages: the content builders, and what the content directory of a package is called. ContentDirectory: the name of the content directory, 'Content' when it is not given; the directory of the content to build is that name with '.bld'. The content an app runs with is in 'Content' of its build area whatever the name is</xs:documentation>
    </xs:annotation>
    <xs:group ref="_G_ContentBuilderConfigurationCommandList"/>
    <xs:attribute name="ContentDirectory" type="xs:string" use="optional"/>
  </xs:complexType>
  

  <xs:group name="_G_ContentBuilder_AddExtension">
    <xs:choice>
      <xs:element name="AddExtension" type="_T_ContentBuilder_AddExtension"/>
    </xs:choice>
  </xs:group>


  <xs:group name="_G_ContentBuilderCommandList">
    <xs:sequence>
      <xs:group ref="_G_ContentBuilder_AddExtension" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:group>


  <xs:group name="_G_ContentBuilder">
    <xs:choice>
      <xs:element name="ContentBuilder" type="_T_ContentBuilder"/>
    </xs:choice>
  </xs:group>


  <xs:group name="_G_ContentBuilderConfigurationCommandList">
    <xs:sequence>
      <xs:group ref="_G_ContentBuilder" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:group>


  <xs:group name="_G_ContentBuilderConfiguration">
    <xs:choice>
      <xs:element name="ContentBuilderConfiguration" type="_T_ContentBuilderConfiguration"/>
    </xs:choice>
  </xs:group>
  

  <xs:group name="_G_TemplateFolder">
    <xs:choice>
      <xs:element name="TemplateFolder" type="_T_TemplateFolder"/>
    </xs:choice>
  </xs:group>


  <xs:group name="_G_GenFile">
    <xs:choice>
      <xs:element name="GenFile" type="_T_GenFile"/>
    </xs:choice>
  </xs:group>


  <xs:group name="_G_AddTemplateImportDirectory">
    <xs:choice>
      <xs:element name="AddTemplateImportDirectory" type="_T_AddTemplateImportDirectory"/>
    </xs:choice>
  </xs:group>
  

  <xs:group name="_G_AddNewProjectTemplatesRootDirectory">
    <xs:choice>
      <xs:element name="AddNewProjectTemplatesRootDirectory" type="_T_AddNewProjectTemplatesRootDirectory"/>
    </xs:choice>
  </xs:group>


  <xs:group name="_G_CommandListAnyNumber">
    <xs:annotation>
      <xs:documentation>The elements of the tool config that can be there any number of times</xs:documentation>
    </xs:annotation>
    <xs:choice>
      <xs:group ref="_G_AddTemplateImportDirectory"/>
      <xs:group ref="_G_AddNewProjectTemplatesRootDirectory"/>
    </xs:choice>
  </xs:group>


  <xs:group name="_G_CommandList">
    <xs:annotation>
      <xs:documentation>The elements of the tool config, in any order. 'GenFile' and 'TemplateFolder' are there once, 'ContentBuilderConfiguration' once at most, which is why each order of the three is written out</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:group ref="_G_CommandListAnyNumber" minOccurs="0" maxOccurs="unbounded"/>
      <xs:choice>
        <xs:sequence>
          <xs:group ref="_G_GenFile"/>
          <xs:group ref="_G_CommandListAnyNumber" minOccurs="0" maxOccurs="unbounded"/>
          <xs:choice>
            <xs:sequence>
              <xs:group ref="_G_TemplateFolder"/>
              <xs:group ref="_G_CommandListAnyNumber" minOccurs="0" maxOccurs="unbounded"/>
              <xs:sequence minOccurs="0">
                <xs:group ref="_G_ContentBuilderConfiguration"/>
                <xs:group ref="_G_CommandListAnyNumber" minOccurs="0" maxOccurs="unbounded"/>
              </xs:sequence>
            </xs:sequence>
            <xs:sequence>
              <xs:group ref="_G_ContentBuilderConfiguration"/>
              <xs:group ref="_G_CommandListAnyNumber" minOccurs="0" maxOccurs="unbounded"/>
              <xs:sequence>
                <xs:group ref="_G_TemplateFolder"/>
                <xs:group ref="_G_CommandListAnyNumber" minOccurs="0" maxOccurs="unbounded"/>
              </xs:sequence>
            </xs:sequence>
          </xs:choice>
        </xs:sequence>
        <xs:sequence>
          <xs:group ref="_G_TemplateFolder"/>
          <xs:group ref="_G_CommandListAnyNumber" minOccurs="0" maxOccurs="unbounded"/>
          <xs:choice>
            <xs:sequence>
              <xs:group ref="_G_GenFile"/>
              <xs:group ref="_G_CommandListAnyNumber" minOccurs="0" maxOccurs="unbounded"/>
              <xs:sequence minOccurs="0">
                <xs:group ref="_G_ContentBuilderConfiguration"/>
                <xs:group ref="_G_CommandListAnyNumber" minOccurs="0" maxOccurs="unbounded"/>
              </xs:sequence>
            </xs:sequence>
            <xs:sequence>
              <xs:group ref="_G_ContentBuilderConfiguration"/>
              <xs:group ref="_G_CommandListAnyNumber" minOccurs="0" maxOccurs="unbounded"/>
              <xs:sequence>
                <xs:group ref="_G_GenFile"/>
                <xs:group ref="_G_CommandListAnyNumber" minOccurs="0" maxOccurs="unbounded"/>
              </xs:sequence>
            </xs:sequence>
          </xs:choice>
        </xs:sequence>
        <xs:sequence>
          <xs:group ref="_G_ContentBuilderConfiguration"/>
          <xs:group ref="_G_CommandListAnyNumber" minOccurs="0" maxOccurs="unbounded"/>
          <xs:choice>
            <xs:sequence>
              <xs:group ref="_G_GenFile"/>
              <xs:group ref="_G_CommandListAnyNumber" minOccurs="0" maxOccurs="unbounded"/>
              <xs:sequence>
                <xs:group ref="_G_TemplateFolder"/>
                <xs:group ref="_G_CommandListAnyNumber" minOccurs="0" maxOccurs="unbounded"/>
              </xs:sequence>
            </xs:sequence>
            <xs:sequence>
              <xs:group ref="_G_TemplateFolder"/>
              <xs:group ref="_G_CommandListAnyNumber" minOccurs="0" maxOccurs="unbounded"/>
              <xs:sequence>
                <xs:group ref="_G_GenFile"/>
                <xs:group ref="_G_CommandListAnyNumber" minOccurs="0" maxOccurs="unbounded"/>
              </xs:sequence>
            </xs:sequence>
          </xs:choice>
        </xs:sequence>
      </xs:choice>
    </xs:sequence>
  </xs:group>


  <xs:complexType name="_T_FslBuildGenConfig">
    <xs:annotation>
      <xs:documentation></xs:documentation>
    </xs:annotation>
    <xs:group ref="_G_CommandList"/>
    <xs:attribute name="Version" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:element name="FslBuildGenConfig" type="_T_FslBuildGenConfig"/>
</xs:schema>

=== Unarmed1000/gtec-demo-framework/.Config/FslBuildGen.xml
<?xml version="1.0" encoding="UTF-8"?>
<FslBuildGenConfig Version="2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FslBuildGenConfig.xsd">
  <GenFile Name="Fsl.gen"/>
  <TemplateFolder Name="$(FSL_GRAPHICS_SDK)/.Config/Templates.gen"/>
  <AddTemplateImportDirectory Name="$(FSL_GRAPHICS_SDK)/.Config/Import.gen"/>
  <AddNewProjectTemplatesRootDirectory Name="$(FSL_GRAPHICS_SDK)/.Config/Templates.gen/NewProject"/>
  <ContentBuilderConfiguration>
    <!-- 
        FeatureRequirements can contain a 'python' like condition statement where the 
        feature names will evaluate to true or false depending on if they are present or not.
    -->
    <ContentBuilder Name="VulkanShaderCompiler" Executable="glslangValidator" Parameters="-t --target-env vulkan1.3 -o $(OutputFileName) -V $(InputFileName)" FeatureRequirements="Vulkan" Description="Vulkan shader compiler used to convert GLSL/HLSL shaders to binary SPIR-V files">
      <AddExtension Name="vert" Description="vertex shader" PostfixedOutputExtension=".spv"/>
      <AddExtension Name="tesc" Description="tessellation control shader" PostfixedOutputExtension=".spv"/>
      <AddExtension Name="tese" Description="tessellation evaluation shader" PostfixedOutputExtension=".spv"/>
      <AddExtension Name="geom" Description="geometry shader" PostfixedOutputExtension=".spv"/>
      <AddExtension Name="frag" Description="fragment shader" PostfixedOutputExtension=".spv"/>
      <AddExtension Name="comp" Description="compute shader" PostfixedOutputExtension=".spv"/>
    </ContentBuilder>
    <ContentBuilder Name="VivanteShaderCompiler" Executable="vCompiler" Parameters="-v -o $(OutputFileName) $(InputFileName)" FeatureRequirements="OpenGLES2 or OpenGLES3" Description="Vivante shader compiler used to compile GLSL shaders to binary files">
      <AddExtension Name="vert" Description="vertex shader"/>
      <AddExtension Name="frag" Description="fragment shader"/>
    </ContentBuilder>
  </ContentBuilderConfiguration>
</FslBuildGenConfig>
